window.BRANDS = [
  {name:'Apple',domain:'apple.com',slug:'apple',category:'Texnologiya'},
  {name:'Microsoft',domain:'microsoft.com',slug:'microsoft',category:'Texnologiya'},
  {name:'Google',domain:'google.com',slug:'google',category:'Texnologiya'},
  {name:'Samsung',domain:'samsung.com',slug:'samsung',category:'Texnologiya'},
  {name:'Sony',domain:'sony.com',slug:'sony',category:'Texnologiya'},
  {name:'LG',domain:'lg.com',slug:'lg',category:'Texnologiya'},
  {name:'Huawei',domain:'huawei.com',slug:'huawei',category:'Texnologiya'},
  {name:'Xiaomi',domain:'mi.com',slug:'xiaomi',category:'Texnologiya'},
  {name:'Nokia',domain:'nokia.com',slug:'nokia',category:'Texnologiya'},
  {name:'Lenovo',domain:'lenovo.com',slug:'lenovo',category:'Texnologiya'},
  {name:'HP',domain:'hp.com',slug:'hp',category:'Texnologiya'},
  {name:'Dell',domain:'dell.com',slug:'dell',category:'Texnologiya'},
  {name:'Intel',domain:'intel.com',slug:'intel',category:'Texnologiya'},
  {name:'NVIDIA',domain:'nvidia.com',slug:'nvidia',category:'Texnologiya'},
  {name:'ASUS',domain:'asus.com',slug:'asus',category:'Texnologiya'},
  {name:'Tesla',domain:'tesla.com',slug:'tesla',category:'Avtomobil'},
  {name:'Toyota',domain:'toyota.com',slug:'toyota',category:'Avtomobil'},
  {name:'Honda',domain:'honda.com',slug:'honda',category:'Avtomobil'},
  {name:'BMW',domain:'bmw.com',slug:'bmw',category:'Avtomobil'},
  {name:'Mercedes-Benz',domain:'mercedes-benz.com',slug:'mercedes',category:'Avtomobil'},
  {name:'Audi',domain:'audi.com',slug:'audi',category:'Avtomobil'},
  {name:'Volkswagen',domain:'volkswagen.com',slug:'volkswagen',category:'Avtomobil'},
  {name:'Ford',domain:'ford.com',slug:'ford',category:'Avtomobil'},
  {name:'Chevrolet',domain:'chevrolet.com',slug:'chevrolet',category:'Avtomobil'},
  {name:'Porsche',domain:'porsche.com',slug:'porsche',category:'Avtomobil'},
  {name:'Ferrari',domain:'ferrari.com',slug:'ferrari',category:'Avtomobil'},
  {name:'Lamborghini',domain:'lamborghini.com',slug:'lamborghini',category:'Avtomobil'},
  {name:'Hyundai',domain:'hyundai.com',slug:'hyundai',category:'Avtomobil'},
  {name:'Kia',domain:'kia.com',slug:'kia',category:'Avtomobil'},
  {name:'Lexus',domain:'lexus.com',slug:'lexus',category:'Avtomobil'},
  {name:'Coca-Cola',domain:'coca-cola.com',slug:'cocacola',category:'Ichimlik va Taom'},
  {name:'Pepsi',domain:'pepsi.com',slug:'pepsi',category:'Ichimlik va Taom'},
  {name:'Red Bull',domain:'redbull.com',slug:'redbull',category:'Ichimlik va Taom'},
  {name:'Sprite',domain:'sprite.com',slug:'sprite',category:'Ichimlik va Taom'},
  {name:'Fanta',domain:'fanta.com',slug:'fanta',category:'Ichimlik va Taom'},
  {name:'Starbucks',domain:'starbucks.com',slug:'starbucks',category:'Ichimlik va Taom'},
  {name:'McDonald\'s',domain:'mcdonalds.com',slug:'mcdonalds',category:'Ichimlik va Taom'},
  {name:'KFC',domain:'kfc.com',slug:'kfc',category:'Ichimlik va Taom'},
  {name:'Burger King',domain:'burgerking.com',slug:'burgerking',category:'Ichimlik va Taom'},
  {name:'Domino\'s',domain:'dominos.com',slug:'dominos',category:'Ichimlik va Taom'},
  {name:'Pizza Hut',domain:'pizzahut.com',slug:'pizzahut',category:'Ichimlik va Taom'},
  {name:'KitKat',domain:'kitkat.com',slug:'kitkat',category:'Ichimlik va Taom'},
  {name:'Oreo',domain:'oreo.com',slug:'oreo',category:'Ichimlik va Taom'},
  {name:'Nutella',domain:'nutella.com',slug:'nutella',category:'Ichimlik va Taom'},
  {name:'Lay\'s',domain:'lays.com',slug:'lays',category:'Ichimlik va Taom'},
  {name:'Nike',domain:'nike.com',slug:'nike',category:'Sport va Moda'},
  {name:'Adidas',domain:'adidas.com',slug:'adidas',category:'Sport va Moda'},
  {name:'Puma',domain:'puma.com',slug:'puma',category:'Sport va Moda'},
  {name:'Reebok',domain:'reebok.com',slug:'reebok',category:'Sport va Moda'},
  {name:'New Balance',domain:'newbalance.com',slug:'newbalance',category:'Sport va Moda'},
  {name:'Gucci',domain:'gucci.com',slug:'gucci',category:'Sport va Moda'},
  {name:'Louis Vuitton',domain:'louisvuitton.com',slug:'louisvuitton',category:'Sport va Moda'},
  {name:'Chanel',domain:'chanel.com',slug:'chanel',category:'Sport va Moda'},
  {name:'Zara',domain:'zara.com',slug:'zara',category:'Sport va Moda'},
  {name:'H&M',domain:'hm.com',slug:'hm',category:'Sport va Moda'},
  {name:'Levi\'s',domain:'levi.com',slug:'levis',category:'Sport va Moda'},
  {name:'Calvin Klein',domain:'calvinklein.com',slug:'calvinklein',category:'Sport va Moda'},
  {name:'Lacoste',domain:'lacoste.com',slug:'lacoste',category:'Sport va Moda'},
  {name:'Dior',domain:'dior.com',slug:'dior',category:'Sport va Moda'},
  {name:'Rolex',domain:'rolex.com',slug:'rolex',category:'Sport va Moda'},
  {name:'Roblox',domain:'roblox.com',slug:'roblox',category:'O‘yin va Ko‘ngilochar'},
  {name:'PlayStation',domain:'playstation.com',slug:'playstation',category:'O‘yin va Ko‘ngilochar'},
  {name:'Xbox',domain:'xbox.com',slug:'xbox',category:'O‘yin va Ko‘ngilochar'},
  {name:'Nintendo',domain:'nintendo.com',slug:'nintendo',category:'O‘yin va Ko‘ngilochar'},
  {name:'Steam',domain:'steampowered.com',slug:'steam',category:'O‘yin va Ko‘ngilochar'},
  {name:'Epic Games',domain:'epicgames.com',slug:'epicgames',category:'O‘yin va Ko‘ngilochar'},
  {name:'Minecraft',domain:'minecraft.net',slug:'minecraft',category:'O‘yin va Ko‘ngilochar'},
  {name:'Rockstar Games',domain:'rockstargames.com',slug:'rockstargames',category:'O‘yin va Ko‘ngilochar'},
  {name:'LEGO',domain:'lego.com',slug:'lego',category:'O‘yin va Ko‘ngilochar'},
  {name:'Disney',domain:'disney.com',slug:'disney',category:'O‘yin va Ko‘ngilochar'},
  {name:'Pixar',domain:'pixar.com',slug:'pixar',category:'O‘yin va Ko‘ngilochar'},
  {name:'Marvel',domain:'marvel.com',slug:'marvel',category:'O‘yin va Ko‘ngilochar'},
  {name:'Netflix',domain:'netflix.com',slug:'netflix',category:'O‘yin va Ko‘ngilochar'},
  {name:'Spotify',domain:'spotify.com',slug:'spotify',category:'O‘yin va Ko‘ngilochar'},
  {name:'Twitch',domain:'twitch.tv',slug:'twitch',category:'O‘yin va Ko‘ngilochar'},
  {name:'YouTube',domain:'youtube.com',slug:'youtube',category:'Ijtimoiy media va Aloqa'},
  {name:'TikTok',domain:'tiktok.com',slug:'tiktok',category:'Ijtimoiy media va Aloqa'},
  {name:'Instagram',domain:'instagram.com',slug:'instagram',category:'Ijtimoiy media va Aloqa'},
  {name:'Facebook',domain:'facebook.com',slug:'facebook',category:'Ijtimoiy media va Aloqa'},
  {name:'X',domain:'x.com',slug:'x',category:'Ijtimoiy media va Aloqa'},
  {name:'LinkedIn',domain:'linkedin.com',slug:'linkedin',category:'Ijtimoiy media va Aloqa'},
  {name:'Snapchat',domain:'snapchat.com',slug:'snapchat',category:'Ijtimoiy media va Aloqa'},
  {name:'WhatsApp',domain:'whatsapp.com',slug:'whatsapp',category:'Ijtimoiy media va Aloqa'},
  {name:'Telegram',domain:'telegram.org',slug:'telegram',category:'Ijtimoiy media va Aloqa'},
  {name:'Reddit',domain:'reddit.com',slug:'reddit',category:'Ijtimoiy media va Aloqa'},
  {name:'Discord',domain:'discord.com',slug:'discord',category:'Ijtimoiy media va Aloqa'},
  {name:'Pinterest',domain:'pinterest.com',slug:'pinterest',category:'Ijtimoiy media va Aloqa'},
  {name:'Amazon',domain:'amazon.com',slug:'amazon',category:'Savdo va Moliya'},
  {name:'eBay',domain:'ebay.com',slug:'ebay',category:'Savdo va Moliya'},
  {name:'Alibaba',domain:'alibaba.com',slug:'alibaba',category:'Savdo va Moliya'},
  {name:'AliExpress',domain:'aliexpress.com',slug:'aliexpress',category:'Savdo va Moliya'},
  {name:'Temu',domain:'temu.com',slug:'temu',category:'Savdo va Moliya'},
  {name:'Shein',domain:'shein.com',slug:'shein',category:'Savdo va Moliya'},
  {name:'IKEA',domain:'ikea.com',slug:'ikea',category:'Savdo va Moliya'},
  {name:'Walmart',domain:'walmart.com',slug:'walmart',category:'Savdo va Moliya'},
  {name:'PayPal',domain:'paypal.com',slug:'paypal',category:'Savdo va Moliya'},
  {name:'Visa',domain:'visa.com',slug:'visa',category:'Savdo va Moliya'},
  {name:'Mastercard',domain:'mastercard.com',slug:'mastercard',category:'Savdo va Moliya'},
  {name:'Binance',domain:'binance.com',slug:'binance',category:'Savdo va Moliya'},
  {name:'Uber',domain:'uber.com',slug:'uber',category:'Sayohat va Xizmat'},
  {name:'Airbnb',domain:'airbnb.com',slug:'airbnb',category:'Sayohat va Xizmat'},
  {name:'Booking.com',domain:'booking.com',slug:'bookingdotcom',category:'Sayohat va Xizmat'},
  {name:'Emirates',domain:'emirates.com',slug:'emirates',category:'Sayohat va Xizmat'},
  {name:'Qatar Airways',domain:'qatarairways.com',slug:'qatarairways',category:'Sayohat va Xizmat'},
  {name:'Turkish Airlines',domain:'turkishairlines.com',slug:'turkishairlines',category:'Sayohat va Xizmat'},
  {name:'DHL',domain:'dhl.com',slug:'dhl',category:'Sayohat va Xizmat'},
  {name:'FedEx',domain:'fedex.com',slug:'fedex',category:'Sayohat va Xizmat'},
  {name:'Dove',domain:'dove.com',slug:'dove',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Nivea',domain:'nivea.com',slug:'nivea',category:'Uy, Go‘zallik va Boshqa'},
  {name:'L\'Oreal',domain:'loreal.com',slug:'loreal',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Garnier',domain:'garnier.com',slug:'garnier',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Maybelline',domain:'maybelline.com',slug:'maybelline',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Colgate',domain:'colgate.com',slug:'colgate',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Bosch',domain:'bosch.com',slug:'bosch',category:'Uy, Go‘zallik va Boshqa'},
  {name:'Philips',domain:'philips.com',slug:'philips',category:'Uy, Go‘zallik va Boshqa'},
  {name:'BBC',domain:'bbc.com',slug:'bbc',category:'Media, Ta’lim va Dastur'},
  {name:'CNN',domain:'cnn.com',slug:'cnn',category:'Media, Ta’lim va Dastur'},
  {name:'National Geographic',domain:'nationalgeographic.com',slug:'nationalgeographic',category:'Media, Ta’lim va Dastur'},
  {name:'Canva',domain:'canva.com',slug:'canva',category:'Media, Ta’lim va Dastur'},
  {name:'ChatGPT',domain:'chatgpt.com',slug:'openai',category:'Media, Ta’lim va Dastur'},
];
